### ISSUE TITLE
Cannot unzip large data file

### ISSUE THREAD

**Issue by PeterZZQ** [caleblareau/asap_reproducibility#1]
I clicked _download as zip_ on the large file, it seemed like the downloaded file cannot be decompressed (maybe broken). Could you please provide an alternative link to download the file? Thanks!

**Comment by caleblareau** [comment]
I've heard from others that it is indeed working, and there's not really another great solution available that I'm aware of to host this data (unless you have something in mind). Can you download a subset of the files and verify that you can unzip those?

**Comment by PeterZZQ** [comment]
Hi, thank you! I'm able to download it after separation. I want to use the data in Fig4b include 2batches of ASAP-Seq and 2batches of CITE-Seq for data integration analysis (totally 8 count matrices). I was wondering where can I directly get those raw count matrices? You use _22July2020_Seurat_Coembed4.rds_ to generate the plot, but it seem like they are processed already (no region for scATAC-Seq data). I observed that in the data folder of `pbmc_stimulation_asapseq_citeseq`, there are some count matrices, can I use them? In addition, I'm a little confused about the scATAC-Seq here. I cannot find the chromatin region name correspond to the count file. 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/37580703/127232388-8c41b1b2-185d-4052-a2af-4cc488ec554f.png">

**Comment by caleblareau** [comment]
Yes— those count matrices are the filtered data from CellRanger for RNA data.

The scATAC data is in the OSF because it was too big for GitHub:

/asap_large_data_files/pbmc_stim_data/input/stim_control_aggr_filtered_peak_bc_matrix.h5

In the h5 file, there are row names that have the accessible chromatin regions (hg38)

On Jul 27, 2021, at 2:53 PM, Peter ***@***.******@***.***>> wrote:


Hi, thank you! I'm able to download it after separation. I want to use the data in Fig4b include 2batches of ASAP-Seq and 2batches of CITE-Seq for data integration analysis (totally 8 count matrices). I was wondering where can I directly get those raw count matrices? You use 22July2020_Seurat_Coembed4.rds to generate the plot, but it seem like they are processed already (no region for scATAC-Seq data). I observed that in the data folder of pbmc_stimulation_asapseq_citeseq, there are some count matrices, can I use them? In addition, I'm a little confused about the scATAC-Seq here. I cannot find the chromatin region name correspond to the count file.
[image]

**Comment by PeterZZQ** [comment]
Hi, I have read the scATAC-Seq matrix, may I know how I can separate it into stim and control batches? The barcode follows the form:
![image](https://user-images.githubusercontent.com/37580703/127374678-55993082-99e3-4d90-b794-f89cf38c185d.png)
Does `-1` in barcodes mean control and `-2` mean stim?

**Comment by caleblareau** [comment]
Correct— the -2 are stimulation and the -1 are control

On Jul 28, 2021, at 11:14 AM, Peter ***@***.******@***.***>> wrote:



Hi, I have read the scATAC-Seq matrix, may I know how I can separate it into stim and control batches? The barcode follows the form:
[image]<https://user-images.githubusercontent.com/37580703/127374678-55993082-99e3-4d90-b794-f89cf38c185d.png>
Does -1 in barcodes mean control and -2 mean stim?

**Comment by PeterZZQ** [comment]
Thank you. It works now, I draw the plot as below, using the label in Seurat result, but it is only cluster id, I was wondering if you have the corresponding cluster annotation too?
<img width="549" alt="image" src="https://user-images.githubusercontent.com/37580703/127388150-2aea6b7c-97d1-4190-98f1-d09ad7515193.png">

**Comment by caleblareau** [comment]
We purposefully didn’t

We purposefully didn’t do a refined annotation of anything— this is as deep as we went:

(c(9,10), “Myeloid")
(c(4), "Bcell")
(c(3), "NK")
(c(0,1,2,5,6,7,8,11), "Tcell")

On Jul 28, 2021, at 1:04 PM, Peter ***@***.******@***.***>> wrote:


Thank you. It works now, I draw the plot as below, using the label in Seurat result, but it is only cluster id, I was wondering if you have the corresponding cluster annotation too?
[image]

**Comment by PeterZZQ** [comment]
Hi, 

When I process the ASAP-Seq data, I find that the label in Seurat result (from _22July2020_Seurat_Coembed4.rds_) doesn't match the raw scATAC-Seq matrix that I read from _stim_control_aggr_filtered_peak_bc_matrix.h5_. There is much less cell in Seurat embedding (3572 ctrl for ATAC, 4963 stim for ATAC) compared to the raw count (6649 ctrl and 7621 stim). Does Seurat embedding filter some cells out? in addition, some barcodes in Seurat result cannot be matched to raw count (around 50-100). Should I drop the not-matched barcodes?

**Comment by caleblareau** [comment]
For this experiment, we wound up calling cells from ArchR (which is slightly different than the 10x execution) and then yeah did more stringent filtering in Seurat. The non-matched barcodes are the rare instances where CellRanger called the barcode a cell and ArchR didn’t. It depends on what you want to do exactly— you can also assemble a new peaks matrix using a variety of different tools for the barcodes indicated.

On Jul 29, 2021, at 12:43 PM, Peter ***@***.******@***.***>> wrote:



Hi,

When I process the ASAP-Seq data, I find that the label in Seurat result (from 22July2020_Seurat_Coembed4.rds) doesn't match the raw scATAC-Seq matrix that I read from stim_control_aggr_filtered_peak_bc_matrix.h5. There is much less cell in Seurat embedding (3572 ctrl for ATAC, 4963 stim for ATAC) compared to the raw count (6649 ctrl and 7621 stim). Does Seurat embedding filter some cells out? in addition, some barcodes in Seurat result cannot be matched to raw count (around 50-100). Should I drop the not-matched barcodes?

**Comment by PeterZZQ** [comment]
Thank you for the detailed explanation! I will use the overlapping barcode for the testing then.
