### ISSUE TITLE
ArchR error with bonemarrow data

### ISSUE THREAD

**Issue by vlink** [caleblareau/asap_reproducibility#2]
Dear all, 

Thank you for developing this amazing new method! We just ran a test and I would like to process our data. In order to get familiar with your pipeline, I decided to run the code you provided for the bone-marrow data. 
However, I get an error generating ArrowFiles. 

_Using GeneAnnotation set by addArchRGenome(Hg38)!
Using GeneAnnotation set by addArchRGenome(Hg38)!
ArchR logging to : ArchRLogs/ArchR-createArrows-9b4372e6924c-Date-2021-08-16_Time-14-57-20.log
If there is an issue, please report to github with logFile!
2021-08-16 14:57:20 : Batch Execution w/ safelapply!, 0 mins elapsed.
Attempting to index /Users/linkvm/Desktop/asap_large_data_files/bonemarrow_data/input as bam...
2021-08-16 14:57:20 : createArrowFiles has encountered an error, checking if any ArrowFiles completed..
ArchR logging successful to : ArchRLogs/ArchR-createArrows-9b4372e6924c-Date-2021-08-16_Time-14-57-20.log_

I am not sure how to proceed from here and was wondering if you have any input?

Thanks!

**Comment by caleblareau** [comment]
Thanks! 

It looks like it’s missing a tabix index, which maybe you can generate using tabix manually? Otherwise, I don’t have a great sense— maybe an ArchR related issue? 

Caleb

**Comment by vlink** [comment]
Thanks for the quick response!

I downloaded the bonemarrow_data from OSF and I was wondering if you could confirm that the files I downloaded are not corrupt?

Here are the md5 checksums of the files I downloaded:
MD5 (BM_asap_v12_hg38-mtMask_mgatk.rds) = 83b935cd1267d1ec793f7b88b7685daf
MD5 (asap_marrow_hg38_fragments.tsv.gz) = c7526a8fc774088e9a908d0749b22c4c
MD5 (asap_marrow_hg38_fragments.tsv.gz.tbi) = 92d366d885376315995297333fb52f36
MD5 (asap_marrow_hg38_raw_peak_bc_matrix.h5) = 7f9898ccbc10ab645211315aefdfd2e7

When you suggested to create a tabix index, are you referring to the asap_marrow_hg38_fragments.tsv.gz.tbi file?

Sorry, I am very new to all of this and not super familiar with the data.

Thanks!

**Comment by caleblareau** [comment]
Hm that looks right then (I was looking into the ArchR log and guessing, but the index does look like it’s there if you have all of that in the same directory). My guess is that this is an error associated with ArchR and I don’t know what best to recommend at this point….
