### ISSUE TITLE
kb_bustool after asap_to_kite

### ISSUE THREAD

**Issue by sohanidassharma123** [caleblareau/asap_reproducibility#3]
Hi, 
Another naive question. I am using kb-kite to process the fastqs (https://www.kallistobus.tools/tutorials/kb_kite/python/kb_kite/), while the code is generating data with example files, with the asap_to_kite generated fastqs it is giving strange result. For example, we have captured 5000 cells in the ASAPSeq, I am getting only length ==500 in the adata object. I am using 737K-cratac-v1.txt whitelist to generate the counts file. I am wondering if the use of this whitelist is creating the problem. 
Sorry for this naive question. I am very new to the field.
Sharing my code, 

python
import pandas as pd
import anndata
import numpy as np
import scanpy as sc
df = pd.read_csv('ASAPSeq003_barcodes.csv')
df[['sequence', 'id']].to_csv('features.tsv', index=None, header=None, sep='\t')
python3.7 /pbtech_mounts/software/apps/kb_python/0.26.4/bin/kb ref -i mismatch.idx -f1 mismatch.fa -g t2g.txt --workflow kite features.tsv 
python3.7 /pbtech_mounts/software/apps/kb_python/0.26.4/bin/kb count --h5ad -i mismatch.idx -g t2g.txt -w 737K-cratac-v1.txt -x 10xv3 --workflow kite -t2 ASAPSeq003_TSA_out_final_R1.fastq.gz ASAPSeq003_TSA_out_final_R2.fastq.gz --overwrite

**Comment by sohanidassharma123** [comment]
Hi, another naive question, this pipeline will automatically consider i5 fastq as input?  Do we need to use reverse complement of the i5 as input?

**Comment by caleblareau** [comment]
For the previous question, I haven't used kb count, so I can't comment on things there unfortunately. 

In terms of reverse complement, this is done by default in the python script in this repository (there is a flag, `--no-rc-R2`, that skips the reverse complement for R2) if you sequence on a miseq or whatever chemsitry
