### ISSUE TITLE
Data file empty

### ISSUE THREAD

**Issue by skr3178** [caleblareau/asap_reproducibility#4]
![image](https://user-images.githubusercontent.com/79299617/189732817-d660ca97-58c1-4af6-9753-314f23c3a128.png)

**Comment by caleblareau** [comment]
Hm strange; the Dropbox is still open here: https://www.dropbox.com/sh/t159z791j8mhp05/AABT1BNXHR4FcBtBmKXOINifa?dl=0

I will try to update the paths, but in the meantime, can you access the data that you need from the dropbox link directly?

**Comment by caleblareau** [comment]
This is fixed now on OSF as well @skr3178

**Comment by skr3178** [comment]
thank you @caleblareau
