### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by maxwellkonnaris** [caleblareau/asap_reproducibility#5]
Hi,

I am a bit new to this type of analysis and Im wondering if you could expand on the readme to help me better understand how to reproduce your results by running the code.

I am trying to replicate figure 5 g-m . Could you explain how to apply your code and what to apply it to? I figured out how to fully download all of your data from OSF (which was troublesome as the zip produces an unreadable file, downloaded from your dropbox which was semi corrupt when unzipping, but fixed by reformatting the zip and unzipping). The data and code are all in the format as stated in the README.

Thank you so much for your help. I apologize for my naivety and lack of understanding! 

Best,
Maxwell

**Comment by caleblareau** [comment]
Great! Glad that you were able to download the data. 

This script does the 3WNN analysis to make the umap coordinates and several of the plots: https://github.com/caleblareau/asap_reproducibility/blob/master/pbmc_stim_multiome/code/11_setup.R

The module scoring (panel j) is here: https://github.com/caleblareau/asap_reproducibility/blob/master/pbmc_stim_multiome/code/13_module_scores.R 

The mtDNA analyses are a bit stand alone and better described in other papers and is somewhat orthogonal as its not a measure of cell state but this is the code: https://github.com/caleblareau/asap_reproducibility/blob/master/pbmc_stim_multiome/code/31_mito_analysis.R

If you have the github and osf folders configured correctly, the basic idea is to open the .R script in the folder and have that path as the working directory. In something like Rstudio, you should just be able to run the code directly and the relative file paths should behave on a unix-based OS.

Hope this helps...

PS- Peter forwarded me your email-- I'll probably be the best point of contact for this
