### ISSUE TITLE
Cannot find ASAP_to_kite.py

### ISSUE THREAD

**Issue by mmohenska** [caleblareau/asap_reproducibility#6]
Hello,

I was reading your publication, particularly the part on how the ASAP-seq was processed, and I was interested in looking at the ASAP_to_kite.py script, however I am having some trouble finding it in the repository. Could I please get some help?

Thanks

**Comment by caleblareau** [comment]
here you go! https://github.com/caleblareau/asap_to_kite

**Comment by mmohenska** [comment]
Thank you!!
