### ISSUE TITLE
Missing DIG_CTRL_per_barcode_metrics.csv.gz File

### ISSUE THREAD

**Issue by liggettla** [caleblareau/asap_reproducibility#7]
I am trying to process CITE-Seq data using your pipeline, and have started running the `pbmc_stim_multiome/01_compare_tag_complexity.R`. I can't figure out where the files live that you are loading here (they don't live in the parent directory `pbmc_stim_multiome` for me): 

```
DIG_ctrl <- estimate_tag_rates("../DIG_ctrl_mo.bustools.tsv", Dc, pbmc_vec)
DIG_stim <- estimate_tag_rates("../DIG_stim_mo.bustools.tsv", Ds, pbmc_vec)
LLL_ctrl <- estimate_tag_rates("../LLL_ctrl_mo.bustools.tsv", Lc, pbmc_vec)
LLL_stim <- estimate_tag_rates("../LLL_stim_mo.bustools.tsv", Ls, pbmc_vec)
```

Are these in the larger datasets hosted on OSF?

(Also hey Caleb 😊 Congrats on the new lab, that's so exciting! I wish you guys all the best.)

**Comment by caleblareau** [comment]
hey! thanks for the kind wishes. hope all is well with you!! 

I similarly can't find these files-- either I renamed them or they got eaten somewhere in the process. These were giant files (like 10GB/file) The rda file that comes up after in that script summarized the key point... A few notes on how I computed these if it helps: 

- map fastqs from GEO https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE166188 with kallisto 
- use bustools to analyze the mapped k-mer tags; specifically, I use the `bustools text` function to get these plaintext files (which is what was
- once you `sort`, you collapse the BUS entries (the PCR duplicates are counted in the 4th row), so you could parse those entries. Instead, I ran `bustools text` after barcode whitelist correction

there is an RDA file in this repo that should hopefully contain the data to remake the plot if it helps?

**Comment by liggettla** [comment]
Perfect, thanks for the help Caleb, I at the very least was able to run through everything just using the subsequent RDA file, to remake the plots. And I'm working through regenerating the files starting with the fastqs from GEO. I appreciate it.
